name: Deploy to Bunny
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Upload script'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Script to Bunny Edge Scripting
        uses: BunnyWay/actions/deploy-script@main
        with:
          script_id: 71838
          deploy_key: bdea5d81-83a5-4007-8b583963d5e1-64c5-4609
          file: "index.js"
